export const ADD_TASK_REQUEST='ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS='ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE='ADD_TASK_FAILURE';

export const GET_TASKS_REQUEST='GETTING_TASKS';
export const GET_TASKS_SUCCESS='GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE='GET_TASKS_FAILURE';

export const GET_TASK_REQUEST='GETTING_TASK';
export const GET_TASK_SUCCESS='GET_TASK_SUCCESS';
export const GET_TASK_FAILURE='GET_TASK_FAILURE';

export const DELETE_TASK_REQUEST='DELETING_TASK';
export const DELETE_TASK_SUCCESS='DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE='DELETE_TASK_FAILURE';

export const DELETE_BULKTASKS_REQUEST='DELETING_BULKTASKS';
export const DELETE_BULKTASKS_SUCCESS='DELETE_BULKTASKS_SUCCESS';
export const DELETE_BULKTASKS_FAILURE='DELETE_BULKTASKS_FAILURE';

export const EDIT_TASK_REQUEST='EDITING_TASK';
export const EDIT_TASK_SUCCESS='EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE='EDIT_TASK_FAILURE';

export const SEND_CONTACTS_REQUEST='SENDING_CONTACTS';
export const SEND_CONTACTS_SUCCESS='SEND_CONTACTS_SUCCESS';
export const SEND_CONTACTS_FAILURE='SEND_CONTACTS_FAILURE';